# Use root/example as user/password credentials
version: '3.8'

services:

  mysql:
    image: mysql:8.0.22
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: atendente
      MYSQL_PASSWORD: atendente
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plano_saude_db